#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: fbbd4e3
#
# Source0 file verified with key 0x021DE40BFB63B406 (nicholas@nicholaswilson.me.uk)
#
Name     : pcre2
Version  : 10.45
Release  : 60
URL      : https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.45/pcre2-10.45.tar.gz
Source0  : https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.45/pcre2-10.45.tar.gz
Source1  : https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.45/pcre2-10.45.tar.gz.sig
Source2  : 021DE40BFB63B406.pkey
Summary  : PCRE2 - Perl compatible regular expressions C library (2nd API) with 16 bit character support
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pcre2-bin = %{version}-%{release}
Requires: pcre2-lib = %{version}-%{release}
Requires: pcre2-license = %{version}-%{release}
Requires: pcre2-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : bzip2-dev
BuildRequires : file
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gnupg
BuildRequires : pkgconfig(valgrind)
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
------------------------------------------------------------------
PCRE2 is a re-working of the original PCRE1 library to provide an entirely new
API. Since its initial release in 2015, there has been further development of
the code and it now differs from PCRE1 in more than just the API. There are new
features, and the internals have been improved. The original PCRE1 library is
now obsolete and no longer maintained. The latest release of PCRE2 is available
in .tar.gz, tar.bz2, or .zip form from this GitHub repository:

%package bin
Summary: bin components for the pcre2 package.
Group: Binaries
Requires: pcre2-license = %{version}-%{release}

%description bin
bin components for the pcre2 package.


%package dev
Summary: dev components for the pcre2 package.
Group: Development
Requires: pcre2-lib = %{version}-%{release}
Requires: pcre2-bin = %{version}-%{release}
Provides: pcre2-devel = %{version}-%{release}
Requires: pcre2 = %{version}-%{release}

%description dev
dev components for the pcre2 package.


%package dev32
Summary: dev32 components for the pcre2 package.
Group: Default
Requires: pcre2-lib32 = %{version}-%{release}
Requires: pcre2-bin = %{version}-%{release}
Requires: pcre2-dev = %{version}-%{release}

%description dev32
dev32 components for the pcre2 package.


%package doc
Summary: doc components for the pcre2 package.
Group: Documentation
Requires: pcre2-man = %{version}-%{release}

%description doc
doc components for the pcre2 package.


%package lib
Summary: lib components for the pcre2 package.
Group: Libraries
Requires: pcre2-license = %{version}-%{release}

%description lib
lib components for the pcre2 package.


%package lib32
Summary: lib32 components for the pcre2 package.
Group: Default
Requires: pcre2-license = %{version}-%{release}

%description lib32
lib32 components for the pcre2 package.


%package license
Summary: license components for the pcre2 package.
Group: Default

%description license
license components for the pcre2 package.


%package man
Summary: man components for the pcre2 package.
Group: Default

%description man
man components for the pcre2 package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 021DE40BFB63B406' gpg.status
%setup -q -n pcre2-10.45
cd %{_builddir}/pcre2-10.45
pushd ..
cp -a pcre2-10.45 build32
popd
pushd ..
cp -a pcre2-10.45 buildavx2
popd
pushd ..
cp -a pcre2-10.45 buildapx
popd

%build
## build_prepend content
export CFLAGS="$CFLAGS -mshstk"
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740081846
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="${CFLAGS_GENERATE}" CXXFLAGS="${CXXFLAGS_GENERATE}" FFLAGS="${FFLAGS_GENERATE}" FCFLAGS="${FCFLAGS_GENERATE}" LDFLAGS="${LDFLAGS_GENERATE}" %configure --disable-static --enable-pcre2-16 \
--enable-pcre2-32 \
--enable-unicode \
--enable-jit=auto
make  %{?_smp_mflags}

make VERBOSE=1 V=1 %{?_smp_mflags} check || :
make clean
export GOAMD64=v2
CFLAGS="${CFLAGS_USE}" CXXFLAGS="${CXXFLAGS_USE}" FFLAGS="${FFLAGS_USE}" FCFLAGS="${FCFLAGS_USE}" LDFLAGS="${LDFLAGS_USE}" %configure --disable-static --enable-pcre2-16 \
--enable-pcre2-32 \
--enable-unicode \
--enable-jit=auto
make  %{?_smp_mflags}

pushd ../build32/
## build_prepend content
export CFLAGS="$CFLAGS -mshstk"
## build_prepend end
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static --enable-pcre2-16 \
--enable-pcre2-32 \
--enable-unicode \
--enable-jit=auto   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
## build_prepend content
export CFLAGS="$CFLAGS -mshstk"
## build_prepend end
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --enable-pcre2-16 \
--enable-pcre2-32 \
--enable-unicode \
--enable-jit=auto
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildapx/
## build_prepend content
export CFLAGS="$CFLAGS -mshstk"
## build_prepend end
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -mapxf -mavx10.1-512 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --host=x86_64-clr-linux-gnu --disable-static --enable-pcre2-16 \
--enable-pcre2-32 \
--enable-unicode \
--enable-jit=auto
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || :
cd ../buildapx;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1740081846
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pcre2
cp %{_builddir}/pcre2-%{version}/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/pcre2/77976f406ba34009d9ba5a43b882fe6de68e5175 || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v3
pushd ../buildapx/
%make_install_va
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/pcre2grep
/V3/usr/bin/pcre2test
/VA/usr/bin/pcre2grep
/VA/usr/bin/pcre2test
/usr/bin/pcre2-config
/usr/bin/pcre2grep
/usr/bin/pcre2test

%files dev
%defattr(-,root,root,-)
/usr/include/pcre2.h
/usr/include/pcre2posix.h
/usr/lib64/libpcre2-16.so
/usr/lib64/libpcre2-32.so
/usr/lib64/libpcre2-8.so
/usr/lib64/libpcre2-posix.so
/usr/lib64/pkgconfig/libpcre2-16.pc
/usr/lib64/pkgconfig/libpcre2-32.pc
/usr/lib64/pkgconfig/libpcre2-8.pc
/usr/lib64/pkgconfig/libpcre2-posix.pc
/usr/share/man/man3/pcre2.3
/usr/share/man/man3/pcre2_callout_enumerate.3
/usr/share/man/man3/pcre2_code_copy.3
/usr/share/man/man3/pcre2_code_copy_with_tables.3
/usr/share/man/man3/pcre2_code_free.3
/usr/share/man/man3/pcre2_compile.3
/usr/share/man/man3/pcre2_compile_context_copy.3
/usr/share/man/man3/pcre2_compile_context_create.3
/usr/share/man/man3/pcre2_compile_context_free.3
/usr/share/man/man3/pcre2_config.3
/usr/share/man/man3/pcre2_convert_context_copy.3
/usr/share/man/man3/pcre2_convert_context_create.3
/usr/share/man/man3/pcre2_convert_context_free.3
/usr/share/man/man3/pcre2_converted_pattern_free.3
/usr/share/man/man3/pcre2_dfa_match.3
/usr/share/man/man3/pcre2_general_context_copy.3
/usr/share/man/man3/pcre2_general_context_create.3
/usr/share/man/man3/pcre2_general_context_free.3
/usr/share/man/man3/pcre2_get_error_message.3
/usr/share/man/man3/pcre2_get_mark.3
/usr/share/man/man3/pcre2_get_match_data_heapframes_size.3
/usr/share/man/man3/pcre2_get_match_data_size.3
/usr/share/man/man3/pcre2_get_ovector_count.3
/usr/share/man/man3/pcre2_get_ovector_pointer.3
/usr/share/man/man3/pcre2_get_startchar.3
/usr/share/man/man3/pcre2_jit_compile.3
/usr/share/man/man3/pcre2_jit_free_unused_memory.3
/usr/share/man/man3/pcre2_jit_match.3
/usr/share/man/man3/pcre2_jit_stack_assign.3
/usr/share/man/man3/pcre2_jit_stack_create.3
/usr/share/man/man3/pcre2_jit_stack_free.3
/usr/share/man/man3/pcre2_maketables.3
/usr/share/man/man3/pcre2_maketables_free.3
/usr/share/man/man3/pcre2_match.3
/usr/share/man/man3/pcre2_match_context_copy.3
/usr/share/man/man3/pcre2_match_context_create.3
/usr/share/man/man3/pcre2_match_context_free.3
/usr/share/man/man3/pcre2_match_data_create.3
/usr/share/man/man3/pcre2_match_data_create_from_pattern.3
/usr/share/man/man3/pcre2_match_data_free.3
/usr/share/man/man3/pcre2_pattern_convert.3
/usr/share/man/man3/pcre2_pattern_info.3
/usr/share/man/man3/pcre2_serialize_decode.3
/usr/share/man/man3/pcre2_serialize_encode.3
/usr/share/man/man3/pcre2_serialize_free.3
/usr/share/man/man3/pcre2_serialize_get_number_of_codes.3
/usr/share/man/man3/pcre2_set_bsr.3
/usr/share/man/man3/pcre2_set_callout.3
/usr/share/man/man3/pcre2_set_character_tables.3
/usr/share/man/man3/pcre2_set_compile_extra_options.3
/usr/share/man/man3/pcre2_set_compile_recursion_guard.3
/usr/share/man/man3/pcre2_set_depth_limit.3
/usr/share/man/man3/pcre2_set_glob_escape.3
/usr/share/man/man3/pcre2_set_glob_separator.3
/usr/share/man/man3/pcre2_set_heap_limit.3
/usr/share/man/man3/pcre2_set_match_limit.3
/usr/share/man/man3/pcre2_set_max_pattern_compiled_length.3
/usr/share/man/man3/pcre2_set_max_pattern_length.3
/usr/share/man/man3/pcre2_set_max_varlookbehind.3
/usr/share/man/man3/pcre2_set_newline.3
/usr/share/man/man3/pcre2_set_offset_limit.3
/usr/share/man/man3/pcre2_set_optimize.3
/usr/share/man/man3/pcre2_set_parens_nest_limit.3
/usr/share/man/man3/pcre2_set_recursion_limit.3
/usr/share/man/man3/pcre2_set_recursion_memory_management.3
/usr/share/man/man3/pcre2_set_substitute_callout.3
/usr/share/man/man3/pcre2_set_substitute_case_callout.3
/usr/share/man/man3/pcre2_substitute.3
/usr/share/man/man3/pcre2_substring_copy_byname.3
/usr/share/man/man3/pcre2_substring_copy_bynumber.3
/usr/share/man/man3/pcre2_substring_free.3
/usr/share/man/man3/pcre2_substring_get_byname.3
/usr/share/man/man3/pcre2_substring_get_bynumber.3
/usr/share/man/man3/pcre2_substring_length_byname.3
/usr/share/man/man3/pcre2_substring_length_bynumber.3
/usr/share/man/man3/pcre2_substring_list_free.3
/usr/share/man/man3/pcre2_substring_list_get.3
/usr/share/man/man3/pcre2_substring_nametable_scan.3
/usr/share/man/man3/pcre2_substring_number_from_name.3
/usr/share/man/man3/pcre2api.3
/usr/share/man/man3/pcre2build.3
/usr/share/man/man3/pcre2callout.3
/usr/share/man/man3/pcre2compat.3
/usr/share/man/man3/pcre2convert.3
/usr/share/man/man3/pcre2demo.3
/usr/share/man/man3/pcre2jit.3
/usr/share/man/man3/pcre2limits.3
/usr/share/man/man3/pcre2matching.3
/usr/share/man/man3/pcre2partial.3
/usr/share/man/man3/pcre2pattern.3
/usr/share/man/man3/pcre2perform.3
/usr/share/man/man3/pcre2posix.3
/usr/share/man/man3/pcre2sample.3
/usr/share/man/man3/pcre2serialize.3
/usr/share/man/man3/pcre2syntax.3
/usr/share/man/man3/pcre2unicode.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libpcre2-16.so
/usr/lib32/libpcre2-32.so
/usr/lib32/libpcre2-8.so
/usr/lib32/libpcre2-posix.so
/usr/lib32/pkgconfig/32libpcre2-16.pc
/usr/lib32/pkgconfig/32libpcre2-32.pc
/usr/lib32/pkgconfig/32libpcre2-8.pc
/usr/lib32/pkgconfig/32libpcre2-posix.pc
/usr/lib32/pkgconfig/libpcre2-16.pc
/usr/lib32/pkgconfig/libpcre2-32.pc
/usr/lib32/pkgconfig/libpcre2-8.pc
/usr/lib32/pkgconfig/libpcre2-posix.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/pcre2/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libpcre2-16.so.0.14.0
/V3/usr/lib64/libpcre2-32.so.0.14.0
/V3/usr/lib64/libpcre2-8.so.0.14.0
/V3/usr/lib64/libpcre2-posix.so.3.0.6
/VA/usr/lib64/libpcre2-16.so.0.14.0
/VA/usr/lib64/libpcre2-32.so.0.14.0
/VA/usr/lib64/libpcre2-8.so.0.14.0
/VA/usr/lib64/libpcre2-posix.so.3.0.6
/usr/lib64/libpcre2-16.so.0
/usr/lib64/libpcre2-16.so.0.14.0
/usr/lib64/libpcre2-32.so.0
/usr/lib64/libpcre2-32.so.0.14.0
/usr/lib64/libpcre2-8.so.0
/usr/lib64/libpcre2-8.so.0.14.0
/usr/lib64/libpcre2-posix.so.3
/usr/lib64/libpcre2-posix.so.3.0.6

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libpcre2-16.so.0
/usr/lib32/libpcre2-16.so.0.14.0
/usr/lib32/libpcre2-32.so.0
/usr/lib32/libpcre2-32.so.0.14.0
/usr/lib32/libpcre2-8.so.0
/usr/lib32/libpcre2-8.so.0.14.0
/usr/lib32/libpcre2-posix.so.3
/usr/lib32/libpcre2-posix.so.3.0.6

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pcre2/77976f406ba34009d9ba5a43b882fe6de68e5175

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pcre2-config.1
/usr/share/man/man1/pcre2grep.1
/usr/share/man/man1/pcre2test.1
